./exp_2_y_parts.sh 1
./exp_2_y_parts.sh 2
./exp_2_y_parts.sh 3
./exp_2_y_parts.sh 4
./exp_2_y_parts.sh 5
./exp_2_y_parts.sh 6
./exp_2_y_parts.sh 7
./exp_2_y_parts.sh 8
./exp_2_y_parts.sh 9
./exp_2_y_parts.sh 10
